# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
archives:
  - format: binary
    files: []
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
